-- local config = {
--   size = 12,
--   shade_filetypes = {},
--   hide_numbers = true,
--   shade_terminals = true,
--   insert_mappings = true,
--   terminal_mappings = true,
--   start_in_insert = true,
--   persist_size = true,
--   close_on_exit = true,
--   direction = "horizontal",
--   shading_factor = nil,
--   shell = vim.o.shell,
--   float_opts = {
--     winblend = 0,
--     highlights = {
--       background = "Normal",
--       border = "Normal",
--     },
--   },
-- }
--

