"\ 这个文件在每次打开.vim文件时调用
"\ 这是在nvim在vim的基础上加的?

"\ 在runtime里有, here i just for learning vim:

    "\ syn keyword vimCommand
    "\ \ contained
    "\     \ a[ppend]
    "\     \ ab[breviate]
    "\     \ abc[lear]
    "\     \ abo[veleft]
    "\     \ al[l]
    "\     \ am[enu]
    "\     \ an[oremenu]
    "\     \ ar[gs]
    "\     \ arga[dd]
    "\     \ argd[elete]
    "\     \ argdo
    "\     \ arge[dit]
    "\     \ argg[lobal]
    "\     \ argl[ocal]
    "\     \ argu[ment]
    "\     \ as[cii]
    "\     \ aun[menu]
    "\     \ b[uffer]
    "\     \ bN[ext]
    "\     \ ba[ll]
    "\     \ bad[d]
    "\     \ bal[t]
    "\     \ bd[elete]
    "\     \ be[have]
    "\     \ bel[owright]
    "\     \ bf[irst]
    "\     \ bl[ast]
    "\     \ bm[odified]
    "\     \ bn[ext]
    "\     \ bo[tright]
    "\     \ bp[revious]
    "\     \ br[ewind]
    "\     \ brea[k]
    "\     \ breaka[dd]
    "\     \ breakd[el]
    "\     \ breakl[ist]
    "\     \ bro[wse]
    "\     \ bu[ffers]
    "\     \ bufd[o]
    "\     \ bun[load]
    "\     \ bw[ipeout]
    "\     \ c[hange]
    "\     \ cN[ext]
    "\     \ cNf[ile]
    "\     \ ca[bbrev]
    "\     \ cabc[lear]
    "\     \ cabo[ve]
    "\     \ cad[dbuffer]
    "\     \ cadde[xpr]
    "\     \ caddf[ile]
    "\     \ caf[ter]
    "\     \ cal[l]
    "\     \ cat[ch]
    "\     \ cb[uffer]
    "\     \ cbe[fore]
    "\     \ cbel[ow]
    "\     \ cbo[ttom]
    "\     \ cc
    "\     \ ccl[ose]
    "\     \ cd
    "\     \ cdo
    "\     \ ce[nter]
    "\     \ cex[pr]
    "\     \ cf[ile]
    "\     \ cfd[o]
    "\     \ cfi[rst]
    "\     \ cg[etfile]
    "\     \ cgetb[uffer]
    "\     \ cgete[xpr]
    "\     \ ch[dir]
    "\     \ cha[nges]
    "\     \ che[ckhealth]
    "\     \ checkp[ath]
    "\     \ checkt[ime]
    "\     \ chi[story]
    "\     \ cl[ist]
    "\     \ cla[st]
    "\     \ clo[se]
    "\     \ cle[arjumps]
    "\     \ cm[ap]
    "\     \ cmapc[lear]
    "\     \ cme[nu]
    "\     \ cn[ext]
    "\     \ cnew[er]
    "\     \ cnf[ile]
    "\     \ cno[remap]
    "\     \ cnorea[bbrev]
    "\
    "\ syn   keyword   vimCommand
    "\ \ contained
    "\     \ cnorem[enu]
    "\     \ co[py]
    "\     \ col[der]
    "\     \ colo[rscheme]
    "\     \ com[mand]
    "\     \ comc[lear]
    "\     \ comp[iler]
    "\     \ con[tinue]
    "\     \ conf[irm]
    "\     \ cons[t]
    "\     \ cop[en]
    "\     \ cp[revious]
    "\     \ cpf[ile]
    "\     \ cq[uit]
    "\     \ cr[ewind]
    "\     \ cs[cope]
    "\     \ cst[ag]
    "\     \ cu[nmap]
    "\     \ cuna[bbrev]
    "\     \ cunm[enu]
    "\     \ cw[indow]
    "\     \ d[elete]
    "\     \ delm[arks]
    "\     \ deb[ug]
    "\     \ debugg[reedy]
    "\     \ del[command]
    "\     \ delf[unction]
    "\     \ di[splay]
    "\     \ dif[fupdate]
    "\     \ diffg[et]
    "\     \ diffo[ff]
    "\     \ diffp[atch]
    "\     \ diffpu[t]
    "\     \ diffs[plit]
    "\     \ difft[his]
    "\     \ dig[raphs]
    "\     \ dj[ump]
    "\     \ dl[ist]
    "\     \ dr[op]
    "\     \ ds[earch]
    "\     \ dsp[lit]
    "\     \ e[dit]
    "\     \ ea[rlier]
    "\     \ ec[ho]
    "\     \ echoe[rr]
    "\     \ echoh[l]
    "\     \ echom[sg]
    "\     \ echon
    "\     \ el[se]
    "\     \ elsei[f]
    "\     \ em[enu]
    "\     \ en[dif]
    "\     \ endf[unction]
    "\     \ endfo[r]
    "\     \ endt[ry]
    "\     \ endw[hile]
    "\     \ ene[w]
    "\     \ ev[al]
    "\     \ ex
    "\     \ exe[cute]
    "\     \ exi[t]
    "\     \ exu[sage]
    "\     \ f[ile]
    "\     \ files
    "\     \ filet[ype]
    "\     \ filt[er]
    "\     \ fin[d]
    "\     \ fina[lly]
    "\     \ fini[sh]
    "\     \ fir[st]
    "\     \ fo[ld]
    "\     \ foldc[lose]
    "\     \ foldd[oopen]
    "\     \ folddoc[losed]
    "\     \ foldo[pen]
    "\     \ for
    "\     \ fu[nction]
    "\     \ g[lobal]
    "\     \ go[to]
    "\     \ gr[ep]
    "\     \ grepa[dd]
    "\     \ gu[i]
    "\     \ gv[im]
    "\     \ h[elp]
    "\     \ helpc[lose]
    "\     \ helpg[rep]
    "\     \ helpt[ags]
    "\
    "\ syn  keyword  vimCommand
    "\ \ contained
    "\     \ ha[rdcopy]
    "\     \ hi[ghlight]
    "\     \ hid[e]
    "\     \ his[tory]
    "\     \ i[nsert]
    "\     \ ia[bbrev]
    "\     \ iabc[lear]
    "\     \ if
    "\     \ ij[ump]
    "\     \ il[ist]
    "\     \ im[ap]
    "\     \ imapc[lear]
    "\     \ ime[nu]
    "\     \ in[oremap]
    "\     \ inorea[bbrev]
    "\     \ inorem[enu]
    "\     \ int[ro]
    "\     \ is[earch]
    "\     \ isp[lit]
    "\     \ iu[nmap]
    "\     \ iuna[bbrev]
    "\     \ iunm[enu]
    "\     \ j[oin]
    "\     \ ju[mps]
    "\     \ k
    "\     \ ke[epmarks]
    "\     \ keepj[umps]
    "\     \ keepp[atterns]
    "\     \ keepa[lt]
    "\     \ l[ist]
    "\     \ lN[ext]
    "\     \ lNf[ile]
    "\     \ la[st]
    "\     \ lab[ove]
    "\     \ lan[guage]
    "\     \ lad[dexpr]
    "\     \ laddb[uffer]
    "\     \ laddf[ile]
    "\     \ laf[ter]
    "\     \ lat[er]
    "\     \ lb[uffer]
    "\     \ lbe[fore]
    "\     \ lbel[ow]
    "\     \ lbo[ttom]
    "\     \ lc[d]
    "\     \ lch[dir]
    "\     \ lcl[ose]
    "\     \ lcs[cope]
    "\     \ ld[o]
    "\     \ le[ft]
    "\     \ lefta[bove]
    "\     \ let
    "\     \ lex[pr]
    "\     \ lf[ile]
    "\     \ lfd[o]
    "\     \ lfi[rst]
    "\     \ lg[etfile]
    "\     \ lgetb[uffer]
    "\     \ lgete[xpr]
    "\     \ lgr[ep]
    "\     \ lgrepa[dd]
    "\     \ lh[elpgrep]
    "\     \ lhi[story]
    "\     \ ll
    "\     \ lla[st]
    "\     \ lli[st]
    "\     \ lm[ap]
    "\     \ lmapc[lear]
    "\     \ lmak[e]
    "\     \ ln[oremap]
    "\     \ lne[xt]
    "\     \ lnew[er]
    "\     \ lnf[ile]
    "\     \ lo[adview]
    "\     \ loadk[eymap]
    "\     \ loc[kmarks]
    "\     \ lockv[ar]
    "\     \ lol[der]
    "\     \ lop[en]
    "\     \ lp[revious]
    "\     \ lpf[ile]
    "\     \ lr[ewind]
    "\     \ lt[ag]
    "\     \ lu[nmap]
    "\     \ lua
    "\     \ luad[o]
    "\     \ luaf[ile]
    "\     \ lv[imgrep]
    "\     \ lvimgrepa[dd]
    "\
    "\ syn   keyword   vimCommand
    "\ \ contained
    "\     \ lw[indow]
    "\     \ ls
    "\     \ m[ove]
    "\     \ ma[rk]
    "\     \ mak[e]
    "\     \ map
    "\     \ mapc[lear]
    "\     \ mar[ks]
    "\     \ mat[ch]
    "\     \ me[nu]
    "\     \ menut[ranslate]
    "\     \ mes[sages]
    "\     \ mk[exrc]
    "\     \ mks[ession]
    "\     \ mksp[ell]
    "\     \ mkv[imrc]
    "\     \ mkvie[w]
    "\     \ mo[de]
    "\     \ mz[scheme]
    "\     \ mzf[ile]
    "\     \ n[ext]
    "\     \ new
    "\     \ nm[ap]
    "\     \ nmapc[lear]
    "\     \ nme[nu]
    "\     \ nn[oremap]
    "\     \ nnoreme[nu]
    "\     \ no[remap]
    "\     \ noa[utocmd]
    "\     \ noh[lsearch]
    "\     \ nor[eabbrev]
    "\     \ norem[enu]
    "\     \ nos[wapfile]
    "\     \ nor[mal]
    "\     \ nu[mber]
    "\     \ nun[map]
    "\     \ nunme[nu]
    "\     \ o[ldfiles]
    "\     \ om[ap]
    "\     \ omapc[lear]
    "\     \ ome[nu]
    "\     \ on[ly]
    "\     \ ono[remap]
    "\     \ onoreme[nu]
    "\     \ op[tions]
    "\     \ ou[nmap]
    "\     \ ounme[nu]
    "\     \ ow[nsyntax]
    "\     \ p[rint]
    "\     \ pa[ckadd]
    "\     \ packl[oadall]
    "\     \ pc[lose]
    "\     \ pe[rl]
    "\     \ perld[o]
    "\     \ perlf[ile]
    "\     \ ped[it]
    "\     \ po[p]
    "\     \ popu[p]
    "\     \ pp[op]
    "\     \ pr[eserve]
    "\     \ prev[ious]
    "\     \ pro[file]
    "\     \ profd[el]
    "\     \ ps[earch]
    "\     \ pt[ag]
    "\     \ ptN[ext]
    "\     \ ptf[irst]
    "\     \ ptj[ump]
    "\     \ ptl[ast]
    "\     \ ptn[ext]
    "\     \ ptp[revious]
    "\     \ ptr[ewind]
    "\     \ pts[elect]
    "\     \ pu[t]
    "\     \ pw[d]
    "\     \ py[thon]
    "\     \ pyd[o]
    "\     \ pyf[ile]
    "\     \ py3
    "\     \ py3d[o]
    "\     \ pyt[hon3]
    "\     \ py3[file]
    "\     \ pyx
    "\     \ pyxd[o]
    "\     \ pyt[honx]
    "\     \ pyx[file]
    "\     \ q[uit]
    "\     \ quita[ll]
    "\     \ qa[ll]
    "\     \ r[ead]
    "\
    "\ syn   keyword   vimCommand
    "\ \ contained
    "\     \ rec[over]
    "\     \ red[o]
    "\     \ redi[r]
    "\     \ redr[aw]
    "\     \ redraws[tatus]
    "\     \ redrawt[abline]
    "\     \ reg[isters]
    "\     \ res[ize]
    "\     \ ret[ab]
    "\     \ retu[rn]
    "\     \ rew[ind]
    "\     \ ri[ght]
    "\     \ rightb[elow]
    "\     \ rs[hada]
    "\     \ ru[ntime]
    "\     \ rund[o]
    "\     \ rub[y]
    "\     \ rubyd[o]
    "\     \ rubyf[ile]
    "\     \ rv[iminfo]
    "\     \ s[ubstitute]
    "\     \ sN[ext]
    "\     \ sa[rgument]
    "\     \ sal[l]
    "\     \ san[dbox]
    "\     \ sav[eas]
    "\     \ sb[uffer]
    "\     \ sbN[ext]
    "\     \ sba[ll]
    "\     \ sbf[irst]
    "\     \ sbl[ast]
    "\     \ sbm[odified]
    "\     \ sbn[ext]
    "\     \ sbp[revious]
    "\     \ sbr[ewind]
    "\     \ sc[riptnames]
    "\     \ scripte[ncoding]
    "\     \ scs[cope]
    "\     \ se[t]
    "\     \ setf[iletype]
    "\     \ setg[lobal]
    "\     \ setl[ocal]
    "\     \ sf[ind]
    "\     \ sfir[st]
    "\     \ si[malt]
    "\     \ sig[n]
    "\     \ sil[ent]
    "\     \ sl[eep]
    "\     \ sla[st]
    "\     \ sm[agic]
    "\     \ smap
    "\     \ smapc[lear]
    "\     \ sme[nu]
    "\     \ sn[ext]
    "\     \ sno[magic]
    "\     \ snor[emap]
    "\     \ snoreme[nu]
    "\     \ so[urce]
    "\     \ sor[t]
    "\     \ sp[lit]
    "\     \ spe[llgood]
    "\     \ spelld[ump]
    "\     \ spelli[nfo]
    "\     \ spellr[epall]
    "\     \ spellra[re]
    "\     \ spellu[ndo]
    "\     \ spellw[rong]
    "\     \ spr[evious]
    "\     \ sr[ewind]
    "\     \ st[op]
    "\     \ sta[g]
    "\     \ star[tinsert]
    "\     \ startg[replace]
    "\     \ startr[eplace]
    "\     \ sto[pinsert]
    "\     \ stj[ump]
    "\     \ sts[elect]
    "\     \ su[nhide]
    "\     \ sunm[ap]
    "\     \ sunme[nu]
    "\
    "\ syn   keyword   vimCommand
    "\ \ contained
    "\     \ sus[pend]
    "\     \ sv[iew]
    "\     \ sw[apname]
    "\     \ sy[ntax]
    "\     \ synti[me]
    "\     \ sync[bind]
    "\     \ t
    "\     \ tc[d]
    "\     \ tch[dir]
    "\     \ tN[ext]
    "\     \ ta[g]
    "\     \ tags
    "\     \ tab
    "\     \ tabc[lose]
    "\     \ tabd[o]
    "\     \ tabe[dit]
    "\     \ tabf[ind]
    "\     \ tabfir[st]
    "\     \ tabm[ove]
    "\     \ tabl[ast]
    "\     \ tabn[ext]
    "\     \ tabnew
    "\     \ tabo[nly]
    "\     \ tabp[revious]
    "\     \ tabN[ext]
    "\     \ tabr[ewind]
    "\     \ tabs
    "\     \ tc[l]
    "\     \ tcld[o]
    "\     \ tclf[ile]
    "\     \ te[rminal]
    "\     \ tf[irst]
    "\     \ th[row]
    "\     \ tj[ump]
    "\     \ tl[ast]
    "\     \ tm[enu]
    "\     \ tma[p]
    "\     \ tmapc[lear]
    "\     \ tn[ext]
    "\     \ tno[remap]
    "\     \ to[pleft]
    "\     \ tp[revious]
    "\     \ tr[ewind]
    "\     \ try
    "\     \ ts[elect]
    "\     \ tu[nmenu]
    "\     \ tunma[p]
    "\     \ u[ndo]
    "\     \ undoj[oin]
    "\     \ undol[ist]
    "\     \ una[bbreviate]
    "\     \ unh[ide]
    "\     \ unl[et]
    "\     \ unlo[ckvar]
    "\     \ unm[ap]
    "\     \ unme[nu]
    "\     \ uns[ilent]
    "\     \ up[date]
    "\     \ v[global]
    "\     \ ve[rsion]
    "\     \ verb[ose]
    "\     \ vert[ical]
    "\     \ vi[sual]
    "\     \ vie[w]
    "\     \ vim[grep]
    "\     \ vimgrepa[dd]
    "\     \ viu[sage]
    "\     \ vm[ap]
    "\     \ vmapc[lear]
    "\     \ vme[nu]
    "\     \ vn[oremap]
    "\     \ vne[w]
    "\     \ vno[remenu]
    "\     \ vs[plit]
    "\     \ vu[nmap]
    "\     \ vunme[nu]
    "\     \ w[rite]
    "\     \ wN[ext]
    "\     \ wa[ll]
    "\     \ wh[ile]
    "\     \ wi[nsize]
    "\     \ winc[md]
    "\     \ wind[o]
    "\     \ winp[os]
    "\     \ wn[ext]
    "\     \ wp[revious]
    "\     \ wq
    "\     \ wqa[ll]
    "\     \ ws[hada]
    "\     \ wu[ndo]
    "\     \ wv[iminfo]
    "\
    "\ syn   keyword   vimCommand
    "\ \ contained
    "\     \ x[it]
    "\     \ xa[ll]
    "\     \ xm[ap]
    "\     \ xmapc[lear]
    "\     \ xme[nu]
    "\     \ xn[oremap]
    "\     \ xnoreme[nu]
    "\     \ xu[nmap]
    "\     \ xunme[nu]
    "\     \ y[ank]
    "\     \ N[ext]
    "\
    "\ syn   keyword   vimOption
    "\ \ contained
    "\     \ aleph
    "\     \ al
    "\     \ arabic
    "\     \ arab
    "\     \ invarabic
    "\     \ noarabic
    "\     \ invarab
    "\     \ noarab
    "\     \ arabicshape
    "\     \ arshape
    "\     \ invarabicshape
    "\     \ noarabicshape
    "\     \ invarshape
    "\     \ noarshape
    "\     \ allowrevins
    "\     \ ari
    "\     \ invallowrevins
    "\     \ noallowrevins
    "\     \ invari
    "\     \ noari
    "\     \ ambiwidth
    "\     \ ambw
    "\     \ autochdir
    "\     \ acd
    "\     \ invautochdir
    "\     \ noautochdir
    "\     \ invacd
    "\     \ noacd
    "\     \ autoindent
    "\     \ ai
    "\     \ invautoindent
    "\     \ noautoindent
    "\     \ invai
    "\     \ noai
    "\     \ autoread
    "\     \ ar
    "\     \ invautoread
    "\     \ noautoread
    "\     \ invar
    "\     \ noar
    "\     \ autowrite
    "\     \ aw
    "\     \ invautowrite
    "\     \ noautowrite
    "\     \ invaw
    "\     \ noaw
    "\     \ autowriteall
    "\     \ awa
    "\     \ invautowriteall
    "\     \ noautowriteall
    "\     \ invawa
    "\     \ noawa
    "\     \ background
    "\     \ bg
    "\     \ backspace
    "\     \ bs
    "\     \ backup
    "\     \ bk
    "\     \ invbackup
    "\     \ nobackup
    "\     \ invbk
    "\     \ nobk
    "\     \ backupcopy
    "\     \ bkc
    "\     \ backupdir
    "\     \ bdir
    "\     \ backupext
    "\     \ bex
    "\     \ backupskip
    "\     \ bsk
    "\     \ belloff
    "\     \ bo
    "\     \ binary
    "\     \ bin
    "\     \ invbinary
    "\     \ nobinary
    "\     \ invbin
    "\     \ nobin
    "\     \ bomb
    "\     \ invbomb
    "\     \ nobomb
    "\     \ breakat
    "\     \ brk
    "\     \ breakindent
    "\     \ bri
    "\     \ invbreakindent
    "\     \ nobreakindent
    "\     \ invbri
    "\     \ nobri
    "\     \ breakindentopt
    "\     \ briopt
    "\     \ browsedir
    "\     \ bsdir
    "\     \ bufhidden
    "\     \ bh
    "\     \ buflisted
    "\     \ bl
    "\     \ invbuflisted
    "\     \ nobuflisted
    "\     \ invbl
    "\     \ nobl
    "\
    "\ syn   keyword   vimOption
    "\ \ contained
    "\     \ buftype
    "\     \ bt
    "\     \ casemap
    "\     \ cmp
    "\     \ cdhome
    "\     \ cdh
    "\     \ invcdhome
    "\     \ nocdhome
    "\     \ invcdh
    "\     \ nocdh
    "\     \ cdpath
    "\     \ cd
    "\     \ cedit
    "\     \ channel
    "\     \ charconvert
    "\     \ ccv
    "\     \ cindent
    "\     \ cin
    "\     \ invcindent
    "\     \ nocindent
    "\     \ invcin
    "\     \ nocin
    "\     \ cinkeys
    "\     \ cink
    "\     \ cinoptions
    "\     \ cino
    "\     \ cinwords
    "\     \ cinw
    "\     \ cinscopedecls
    "\     \ cinsd
    "\     \ clipboard
    "\     \ cb
    "\     \ cmdheight
    "\     \ ch
    "\     \ cmdwinheight
    "\     \ cwh
    "\     \ colorcolumn
    "\     \ cc
    "\     \ columns
    "\     \ co
    "\     \ comments
    "\     \ com
    "\     \ commentstring
    "\     \ cms
    "\     \ complete
    "\     \ cpt
    "\     \ concealcursor
    "\     \ cocu
    "\     \ conceallevel
    "\     \ cole
    "\     \ completefunc
    "\     \ cfu
    "\     \ completeopt
    "\     \ cot
    "\     \ completeslash
    "\     \ csl
    "\     \ confirm
    "\     \ cf
    "\     \ invconfirm
    "\     \ noconfirm
    "\     \ invcf
    "\     \ nocf
    "\     \ copyindent
    "\     \ ci
    "\     \ invcopyindent
    "\     \ nocopyindent
    "\     \ invci
    "\     \ noci
    "\     \ cpoptions
    "\     \ cpo
    "\     \ cscopepathcomp
    "\     \ cspc
    "\     \ cscopeprg
    "\     \ csprg
    "\     \ cscopequickfix
    "\     \ csqf
    "\     \ cscoperelative
    "\     \ csre
    "\     \ invcscoperelative
    "\     \ nocscoperelative
    "\     \ invcsre
    "\     \ nocsre
    "\     \ cscopetag
    "\     \ cst
    "\     \ invcscopetag
    "\     \ nocscopetag
    "\     \ invcst
    "\     \ nocst
    "\     \ cscopetagorder
    "\     \ csto
    "\     \ cscopeverbose
    "\     \ csverb
    "\     \ invcscopeverbose
    "\     \ nocscopeverbose
    "\     \ invcsverb
    "\     \ nocsverb
    "\     \ cursorbind
    "\     \ crb
    "\     \ invcursorbind
    "\     \ nocursorbind
    "\     \ invcrb
    "\     \ nocrb
    "\
    "\ syn   keyword   vimOption
    "\ \ contained
    "\     \ cursorcolumn
    "\     \ cuc
    "\     \ invcursorcolumn
    "\     \ nocursorcolumn
    "\     \ invcuc
    "\     \ nocuc
    "\     \ cursorline
    "\     \ cul
    "\     \ invcursorline
    "\     \ nocursorline
    "\     \ invcul
    "\     \ nocul
    "\     \ cursorlineopt
    "\     \ culopt
    "\     \ debug
    "\     \ define
    "\     \ def
    "\     \ delcombine
    "\     \ deco
    "\     \ invdelcombine
    "\     \ nodelcombine
    "\     \ invdeco
    "\     \ nodeco
    "\     \ dictionary
    "\     \ dict
    "\     \ diff
    "\     \ invdiff
    "\     \ nodiff
    "\     \ diffexpr
    "\     \ dex
    "\     \ diffopt
    "\     \ dip
    "\     \ digraph
    "\     \ dg
    "\     \ invdigraph
    "\     \ nodigraph
    "\     \ invdg
    "\     \ nodg
    "\     \ directory
    "\     \ dir
    "\     \ display
    "\     \ dy
    "\     \ eadirection
    "\     \ ead
    "\     \ emoji
    "\     \ emo
    "\     \ invemoji
    "\     \ noemoji
    "\     \ invemo
    "\     \ noemo
    "\     \ encoding
    "\     \ enc
    "\     \ endofline
    "\     \ eol
    "\     \ invendofline
    "\     \ noendofline
    "\     \ inveol
    "\     \ noeol
    "\     \ equalalways
    "\     \ ea
    "\     \ invequalalways
    "\     \ noequalalways
    "\     \ invea
    "\     \ noea
    "\     \ equalprg
    "\     \ ep
    "\     \ errorbells
    "\     \ eb
    "\     \ inverrorbells
    "\     \ noerrorbells
    "\     \ inveb
    "\     \ noeb
    "\     \ errorfile
    "\     \ ef
    "\     \ errorformat
    "\     \ efm
    "\     \ eventignore
    "\     \ ei
    "\     \ expandtab
    "\     \ et
    "\     \ invexpandtab
    "\     \ noexpandtab
    "\     \ invet
    "\     \ noet
    "\     \ exrc
    "\     \ ex
    "\     \ invexrc
    "\     \ noexrc
    "\     \ invex
    "\     \ noex
    "\     \ fileencoding
    "\     \ fenc
    "\     \ fileencodings
    "\     \ fencs
    "\     \ fileformat
    "\     \ ff
    "\     \ fileformats
    "\     \ ffs
    "\     \ fileignorecase
    "\     \ fic
    "\     \ invfileignorecase
    "\     \ nofileignorecase
    "\     \ invfic
    "\     \ nofic
    "\
    "\ syn   keyword   vimOption
    "\ \ contained
    "\     \ filetype
    "\     \ ft
    "\     \ fillchars
    "\     \ fcs
    "\     \ fixendofline
    "\     \ fixeol
    "\     \ invfixendofline
    "\     \ nofixendofline
    "\     \ invfixeol
    "\     \ nofixeol
    "\     \ foldclose
    "\     \ fcl
    "\     \ foldcolumn
    "\     \ fdc
    "\     \ foldenable
    "\     \ fen
    "\     \ invfoldenable
    "\     \ nofoldenable
    "\     \ invfen
    "\     \ nofen
    "\     \ foldexpr
    "\     \ fde
    "\     \ foldignore
    "\     \ fdi
    "\     \ foldlevel
    "\     \ fdl
    "\     \ foldlevelstart
    "\     \ fdls
    "\     \ foldmarker
    "\     \ fmr
    "\     \ foldmethod
    "\     \ fdm
    "\     \ foldminlines
    "\     \ fml
    "\     \ foldnestmax
    "\     \ fdn
    "\     \ foldopen
    "\     \ fdo
    "\     \ foldtext
    "\     \ fdt
    "\     \ formatexpr
    "\     \ fex
    "\     \ formatoptions
    "\     \ fo
    "\     \ formatlistpat
    "\     \ flp
    "\     \ formatprg
    "\     \ fp
    "\     \ fsync
    "\     \ fs
    "\     \ invfsync
    "\     \ nofsync
    "\     \ invfs
    "\     \ nofs
    "\     \ gdefault
    "\     \ gd
    "\     \ invgdefault
    "\     \ nogdefault
    "\     \ invgd
    "\     \ nogd
    "\     \ grepformat
    "\     \ gfm
    "\     \ grepprg
    "\     \ gp
    "\     \ guicursor
    "\     \ gcr
    "\     \ guifont
    "\     \ gfn
    "\     \ guifontwide
    "\     \ gfw
    "\     \ guioptions
    "\     \ go
    "\     \ guitablabel
    "\     \ gtl
    "\     \ guitabtooltip
    "\     \ gtt
    "\     \ helpfile
    "\     \ hf
    "\     \ helpheight
    "\     \ hh
    "\     \ helplang
    "\     \ hlg
    "\     \ hidden
    "\     \ hid
    "\     \ invhidden
    "\     \ nohidden
    "\     \ invhid
    "\     \ nohid
    "\     \ highlight
    "\     \ hl
    "\     \ history
    "\     \ hi
    "\     \ hkmap
    "\     \ hk
    "\     \ invhkmap
    "\     \ nohkmap
    "\     \ invhk
    "\     \ nohk
    "\     \ hkmapp
    "\     \ hkp
    "\     \ invhkmapp
    "\     \ nohkmapp
    "\     \ invhkp
    "\     \ nohkp
    "\     \ hlsearch
    "\     \ hls
    "\     \ invhlsearch
    "\     \ nohlsearch
    "\     \ invhls
    "\     \ nohls
    "\
    "\ syn   keyword   vimOption
    "\ \ contained
    "\     \ icon
    "\     \ invicon
    "\     \ noicon
    "\     \ iconstring
    "\     \ ignorecase
    "\     \ ic
    "\     \ invignorecase
    "\     \ noignorecase
    "\     \ invic
    "\     \ noic
    "\     \ imcmdline
    "\     \ imc
    "\     \ invimcmdline
    "\     \ noimcmdline
    "\     \ invimc
    "\     \ noimc
    "\     \ imdisable
    "\     \ imd
    "\     \ invimdisable
    "\     \ noimdisable
    "\     \ invimd
    "\     \ noimd
    "\     \ iminsert
    "\     \ imi
    "\     \ imsearch
    "\     \ ims
    "\     \ inccommand
    "\     \ icm
    "\     \ include
    "\     \ inc
    "\     \ includeexpr
    "\     \ inex
    "\     \ incsearch
    "\     \ is
    "\     \ invincsearch
    "\     \ noincsearch
    "\     \ invis
    "\     \ nois
    "\     \ indentexpr
    "\     \ inde
    "\     \ indentkeys
    "\     \ indk
    "\     \ infercase
    "\     \ inf
    "\     \ invinfercase
    "\     \ noinfercase
    "\     \ invinf
    "\     \ noinf
    "\     \ insertmode
    "\     \ im
    "\     \ invinsertmode
    "\     \ noinsertmode
    "\     \ invim
    "\     \ noim
    "\     \ isfname
    "\     \ isf
    "\     \ isident
    "\     \ isi
    "\     \ iskeyword
    "\     \ isk
    "\     \ isprint
    "\     \ isp
    "\     \ joinspaces
    "\     \ js
    "\     \ invjoinspaces
    "\     \ nojoinspaces
    "\     \ invjs
    "\     \ nojs
    "\     \ jumpoptions
    "\     \ jop
    "\     \ keymap
    "\     \ kmp
    "\     \ keymodel
    "\     \ km
    "\     \ keywordprg
    "\     \ kp
    "\     \ langmap
    "\     \ lmap
    "\     \ langmenu
    "\     \ lm
    "\     \ langnoremap
    "\     \ lnr
    "\     \ invlangnoremap
    "\     \ nolangnoremap
    "\     \ invlnr
    "\     \ nolnr
    "\     \ langremap
    "\     \ lrm
    "\     \ invlangremap
    "\     \ nolangremap
    "\     \ invlrm
    "\     \ nolrm
    "\     \ laststatus
    "\     \ ls
    "\     \ lazyredraw
    "\     \ lz
    "\     \ invlazyredraw
    "\     \ nolazyredraw
    "\     \ invlz
    "\     \ nolz
    "\     \ linebreak
    "\     \ lbr
    "\     \ invlinebreak
    "\     \ nolinebreak
    "\     \ invlbr
    "\     \ nolbr
    "\
    "\ syn   keyword   vimOption
    "\ \ contained
    "\     \ lines
    "\     \ linespace
    "\     \ lsp
    "\     \ lisp
    "\     \ invlisp
    "\     \ nolisp
    "\     \ lispwords
    "\     \ lw
    "\     \ list
    "\     \ invlist
    "\     \ nolist
    "\     \ listchars
    "\     \ lcs
    "\     \ loadplugins
    "\     \ lpl
    "\     \ invloadplugins
    "\     \ noloadplugins
    "\     \ invlpl
    "\     \ nolpl
    "\     \ magic
    "\     \ invmagic
    "\     \ nomagic
    "\     \ makeef
    "\     \ mef
    "\     \ makeencoding
    "\     \ menc
    "\     \ makeprg
    "\     \ mp
    "\     \ matchpairs
    "\     \ mps
    "\     \ matchtime
    "\     \ mat
    "\     \ maxcombine
    "\     \ mco
    "\     \ maxfuncdepth
    "\     \ mfd
    "\     \ maxmapdepth
    "\     \ mmd
    "\     \ maxmempattern
    "\     \ mmp
    "\     \ menuitems
    "\     \ mis
    "\     \ mkspellmem
    "\     \ msm
    "\     \ modeline
    "\     \ ml
    "\     \ invmodeline
    "\     \ nomodeline
    "\     \ invml
    "\     \ noml
    "\     \ modelineexpr
    "\     \ mle
    "\     \ invmodelineexpr
    "\     \ nomodelineexpr
    "\     \ invmle
    "\     \ nomle
    "\     \ modelines
    "\     \ mls
    "\     \ modifiable
    "\     \ ma
    "\     \ invmodifiable
    "\     \ nomodifiable
    "\     \ invma
    "\     \ noma
    "\     \ modified
    "\     \ mod
    "\     \ invmodified
    "\     \ nomodified
    "\     \ invmod
    "\     \ nomod
    "\     \ more
    "\     \ invmore
    "\     \ nomore
    "\     \ mouse
    "\     \ mousefocus
    "\     \ mousef
    "\     \ invmousefocus
    "\     \ nomousefocus
    "\     \ invmousef
    "\     \ nomousef
    "\     \ mousehide
    "\     \ mh
    "\     \ invmousehide
    "\     \ nomousehide
    "\     \ invmh
    "\     \ nomh
    "\     \ mousemodel
    "\     \ mousem
    "\     \ mouseshape
    "\     \ mouses
    "\     \ mousetime
    "\     \ mouset
    "\     \ nrformats
    "\     \ nf
    "\     \ number
    "\     \ nu
    "\     \ invnumber
    "\     \ nonumber
    "\     \ invnu
    "\     \ nonu
    "\     \ numberwidth
    "\     \ nuw
    "\     \ omnifunc
    "\     \ ofu
    "\
    "\ syn   keyword   vimOption
    "\ \ contained
    "\     \ opendevice
    "\     \ odev
    "\     \ invopendevice
    "\     \ noopendevice
    "\     \ invodev
    "\     \ noodev
    "\     \ operatorfunc
    "\     \ opfunc
    "\     \ packpath
    "\     \ pp
    "\     \ paragraphs
    "\     \ para
    "\     \ paste
    "\     \ invpaste
    "\     \ nopaste
    "\     \ pastetoggle
    "\     \ pt
    "\     \ patchexpr
    "\     \ pex
    "\     \ patchmode
    "\     \ pm
    "\     \ path
    "\     \ pa
    "\     \ preserveindent
    "\     \ pi
    "\     \ invpreserveindent
    "\     \ nopreserveindent
    "\     \ invpi
    "\     \ nopi
    "\     \ previewheight
    "\     \ pvh
    "\     \ previewwindow
    "\     \ pvw
    "\     \ invpreviewwindow
    "\     \ nopreviewwindow
    "\     \ invpvw
    "\     \ nopvw
    "\     \ printdevice
    "\     \ pdev
    "\     \ printencoding
    "\     \ penc
    "\     \ printexpr
    "\     \ pexpr
    "\     \ printfont
    "\     \ pfn
    "\     \ printheader
    "\     \ pheader
    "\     \ printmbcharset
    "\     \ pmbcs
    "\     \ printmbfont
    "\     \ pmbfn
    "\     \ printoptions
    "\     \ popt
    "\     \ pumblend
    "\     \ pb
    "\     \ pumheight
    "\     \ ph
    "\     \ pumwidth
    "\     \ pw
    "\     \ pyxversion
    "\     \ pyx
    "\     \ quickfixtextfunc
    "\     \ qftf
    "\     \ quoteescape
    "\     \ qe
    "\     \ readonly
    "\     \ ro
    "\     \ invreadonly
    "\     \ noreadonly
    "\     \ invro
    "\     \ noro
    "\     \ redrawdebug
    "\     \ rdb
    "\     \ redrawtime
    "\     \ rdt
    "\     \ regexpengine
    "\     \ re
    "\     \ relativenumber
    "\     \ rnu
    "\     \ invrelativenumber
    "\     \ norelativenumber
    "\     \ invrnu
    "\     \ nornu
    "\     \ remap
    "\     \ invremap
    "\     \ noremap
    "\     \ report
    "\     \ revins
    "\     \ ri
    "\     \ invrevins
    "\     \ norevins
    "\     \ invri
    "\     \ nori
    "\     \ rightleft
    "\     \ rl
    "\     \ invrightleft
    "\     \ norightleft
    "\     \ invrl
    "\     \ norl
    "\
    "\ syn
    "\     \ keyword
    "\     \ vimOption
    "\     \ contained
    "\     \ rightleftcmd
    "\     \ rlc
    "\     \ ruler
    "\     \ ru
    "\     \ invruler
    "\     \ noruler
    "\     \ invru
    "\     \ noru
    "\     \ rulerformat
    "\     \ ruf
    "\     \ runtimepath
    "\     \ rtp
    "\     \ scroll
    "\     \ scr
    "\     \ scrollback
    "\     \ scbk
    "\     \ scrollbind
    "\     \ scb
    "\     \ invscrollbind
    "\     \ noscrollbind
    "\     \ invscb
    "\     \ noscb
    "\     \ scrolljump
    "\     \ sj
    "\     \ scrolloff
    "\     \ so
    "\     \ scrollopt
    "\     \ sbo
    "\     \ sections
    "\     \ sect
    "\     \ secure
    "\     \ invsecure
    "\     \ nosecure
    "\     \ selection
    "\     \ sel
    "\     \ selectmode
    "\     \ slm
    "\     \ sessionoptions
    "\     \ ssop
    "\     \ shada
    "\     \ sd
    "\     \ shadafile
    "\     \ sdf
    "\     \ shell
    "\     \ sh
    "\     \ shellcmdflag
    "\     \ shcf
    "\     \ shellpipe
    "\     \ sp
    "\     \ shellquote
    "\     \ shq
    "\     \ shellredir
    "\     \ srr
    "\     \ shellslash
    "\     \ ssl
    "\     \ invshellslash
    "\     \ noshellslash
    "\     \ invssl
    "\     \ nossl
    "\     \ shelltemp
    "\     \ stmp
    "\     \ invshelltemp
    "\     \ noshelltemp
    "\     \ invstmp
    "\     \ nostmp
    "\     \ shellxquote
    "\     \ sxq
    "\     \ shellxescape
    "\     \ sxe
    "\     \ shiftround
    "\     \ sr
    "\     \ invshiftround
    "\     \ noshiftround
    "\     \ invsr
    "\     \ nosr
    "\     \ shiftwidth
    "\     \ sw
    "\     \ shortmess
    "\     \ shm
    "\     \ showbreak
    "\     \ sbr
    "\     \ showcmd
    "\     \ sc
    "\     \ invshowcmd
    "\     \ noshowcmd
    "\     \ invsc
    "\     \ nosc
    "\     \ showfulltag
    "\     \ sft
    "\     \ invshowfulltag
    "\     \ noshowfulltag
    "\     \ invsft
    "\     \ nosft
    "\     \ showmatch
    "\     \ sm
    "\     \ invshowmatch
    "\     \ noshowmatch
    "\     \ invsm
    "\     \ nosm
    "\     \ showmode
    "\     \ smd
    "\     \ invshowmode
    "\     \ noshowmode
    "\     \ invsmd
    "\     \ nosmd
    "\
    "\ syn
    "\     \ keyword
    "\     \ vimOption
    "\     \ contained
    "\     \ showtabline
    "\     \ stal
    "\     \ sidescroll
    "\     \ ss
    "\     \ sidescrolloff
    "\     \ siso
    "\     \ signcolumn
    "\     \ scl
    "\     \ smartcase
    "\     \ scs
    "\     \ invsmartcase
    "\     \ nosmartcase
    "\     \ invscs
    "\     \ noscs
    "\     \ smartindent
    "\     \ si
    "\     \ invsmartindent
    "\     \ nosmartindent
    "\     \ invsi
    "\     \ nosi
    "\     \ smarttab
    "\     \ sta
    "\     \ invsmarttab
    "\     \ nosmarttab
    "\     \ invsta
    "\     \ nosta
    "\     \ softtabstop
    "\     \ sts
    "\     \ spell
    "\     \ invspell
    "\     \ nospell
    "\     \ spellcapcheck
    "\     \ spc
    "\     \ spellfile
    "\     \ spf
    "\     \ spelllang
    "\     \ spl
    "\     \ spellsuggest
    "\     \ sps
    "\     \ spelloptions
    "\     \ spo
    "\     \ splitbelow
    "\     \ sb
    "\     \ invsplitbelow
    "\     \ nosplitbelow
    "\     \ invsb
    "\     \ nosb
    "\     \ splitright
    "\     \ spr
    "\     \ invsplitright
    "\     \ nosplitright
    "\     \ invspr
    "\     \ nospr
    "\     \ startofline
    "\     \ sol
    "\     \ invstartofline
    "\     \ nostartofline
    "\     \ invsol
    "\     \ nosol
    "\     \ statusline
    "\     \ stl
    "\     \ suffixes
    "\     \ su
    "\     \ suffixesadd
    "\     \ sua
    "\     \ swapfile
    "\     \ swf
    "\     \ invswapfile
    "\     \ noswapfile
    "\     \ invswf
    "\     \ noswf
    "\     \ switchbuf
    "\     \ swb
    "\     \ synmaxcol
    "\     \ smc
    "\     \ syntax
    "\     \ syn
    "\     \ tagfunc
    "\     \ tfu
    "\     \ tabline
    "\     \ tal
    "\     \ tabpagemax
    "\     \ tpm
    "\     \ tabstop
    "\     \ ts
    "\     \ tagbsearch
    "\     \ tbs
    "\     \ invtagbsearch
    "\     \ notagbsearch
    "\     \ invtbs
    "\     \ notbs
    "\     \ tagcase
    "\     \ tc
    "\     \ taglength
    "\     \ tl
    "\     \ tagrelative
    "\     \ tr
    "\     \ invtagrelative
    "\     \ notagrelative
    "\     \ invtr
    "\     \ notr
    "\
    "\ syn
    "\     \ keyword
    "\     \ vimOption
    "\     \ contained
    "\     \ tags
    "\     \ tag
    "\     \ tagstack
    "\     \ tgst
    "\     \ invtagstack
    "\     \ notagstack
    "\     \ invtgst
    "\     \ notgst
    "\     \ termbidi
    "\     \ tbidi
    "\     \ invtermbidi
    "\     \ notermbidi
    "\     \ invtbidi
    "\     \ notbidi
    "\     \ termencoding
    "\     \ tenc
    "\     \ termguicolors
    "\     \ tgc
    "\     \ invtermguicolors
    "\     \ notermguicolors
    "\     \ invtgc
    "\     \ notgc
    "\     \ termpastefilter
    "\     \ tpf
    "\     \ terse
    "\     \ invterse
    "\     \ noterse
    "\     \ textwidth
    "\     \ tw
    "\     \ thesaurus
    "\     \ tsr
    "\     \ thesaurusfunc
    "\     \ tsrfu
    "\     \ tildeop
    "\     \ top
    "\     \ invtildeop
    "\     \ notildeop
    "\     \ invtop
    "\     \ notop
    "\     \ timeout
    "\     \ to
    "\     \ invtimeout
    "\     \ notimeout
    "\     \ invto
    "\     \ noto
    "\     \ timeoutlen
    "\     \ tm
    "\     \ title
    "\     \ invtitle
    "\     \ notitle
    "\     \ titlelen
    "\     \ titleold
    "\     \ titlestring
    "\     \ ttimeout
    "\     \ invttimeout
    "\     \ nottimeout
    "\     \ ttimeoutlen
    "\     \ ttm
    "\     \ undodir
    "\     \ udir
    "\     \ undofile
    "\     \ udf
    "\     \ invundofile
    "\     \ noundofile
    "\     \ invudf
    "\     \ noudf
    "\     \ undolevels
    "\     \ ul
    "\     \ undoreload
    "\     \ ur
    "\     \ updatecount
    "\     \ uc
    "\     \ updatetime
    "\     \ ut
    "\     \ varsofttabstop
    "\     \ vsts
    "\     \ vartabstop
    "\     \ vts
    "\     \ verbose
    "\     \ vbs
    "\     \ verbosefile
    "\     \ vfile
    "\     \ viewdir
    "\     \ vdir
    "\     \ viewoptions
    "\     \ vop
    "\     \ viminfo
    "\     \ vi
    "\     \ viminfofile
    "\     \ vif
    "\     \ virtualedit
    "\     \ ve
    "\     \ visualbell
    "\     \ vb
    "\     \ invvisualbell
    "\     \ novisualbell
    "\     \ invvb
    "\     \ novb
    "\     \ warn
    "\     \ invwarn
    "\     \ nowarn
    "\
    "\ syn   keyword   vimOption
    "\ \ contained
    "\     \ whichwrap
    "\     \ ww
    "\     \ wildchar
    "\     \ wc
    "\     \ wildcharm
    "\     \ wcm
    "\     \ wildignore
    "\     \ wig
    "\     \ wildignorecase
    "\     \ wic
    "\     \ invwildignorecase
    "\     \ nowildignorecase
    "\     \ invwic
    "\     \ nowic
    "\     \ wildmenu
    "\     \ wmnu
    "\     \ invwildmenu
    "\     \ nowildmenu
    "\     \ invwmnu
    "\     \ nowmnu
    "\     \ wildmode
    "\     \ wim
    "\     \ wildoptions
    "\     \ wop
    "\     \ winaltkeys
    "\     \ wak
    "\     \ winblend
    "\     \ winbl
    "\     \ winhighlight
    "\     \ winhl
    "\     \ window
    "\     \ wi
    "\     \ winheight
    "\     \ wh
    "\     \ winfixheight
    "\     \ wfh
    "\     \ invwinfixheight
    "\     \ nowinfixheight
    "\     \ invwfh
    "\     \ nowfh
    "\     \ winfixwidth
    "\     \ wfw
    "\     \ invwinfixwidth
    "\     \ nowinfixwidth
    "\     \ invwfw
    "\     \ nowfw
    "\     \ winminheight
    "\     \ wmh
    "\     \ winminwidth
    "\     \ wmw
    "\     \ winwidth
    "\     \ wiw
    "\     \ wrap
    "\     \ invwrap
    "\     \ nowrap
    "\     \ wrapmargin
    "\     \ wm
    "\     \ wrapscan
    "\     \ ws
    "\     \ invwrapscan
    "\     \ nowrapscan
    "\     \ invws
    "\     \ nows
    "\     \ write
    "\     \ invwrite
    "\     \ nowrite
    "\     \ writeany
    "\     \ wa
    "\     \ invwriteany
    "\     \ nowriteany
    "\     \ invwa
    "\     \ nowa
    "\     \ writebackup
    "\     \ wb
    "\     \ invwritebackup
    "\     \ nowritebackup
    "\     \ invwb
    "\     \ nowb
    "\     \ writedelay
    "\     \ wd
    "\
    "\ syn  case   ignore
    "\
    "\ syn  keyword  vimAutoEvent
    "\     \ contained
    "\     \ BufAdd
    "\     \ BufDelete
    "\     \ BufEnter
    "\     \ BufFilePost
    "\     \ BufFilePre
    "\     \ BufHidden
    "\     \ BufLeave
    "\     \ BufNew
    "\     \ BufNewFile
    "\     \ BufReadCmd
    "\     \ BufReadPost
    "\     \ BufReadPre
    "\     \ BufUnload
    "\     \ BufWinEnter
    "\     \ BufWinLeave
    "\     \ BufWipeout
    "\     \ BufWriteCmd
    "\     \ BufWritePost
    "\     \ BufWritePre
    "\     \ ChanInfo
    "\     \ ChanOpen
    "\     \ CmdUndefined
    "\     \ CmdWinEnter
    "\     \ CmdWinLeave
    "\     \ CmdlineChanged
    "\     \ CmdlineEnter
    "\     \ CmdlineLeave
    "\     \ ColorScheme
    "\     \ ColorSchemePre
    "\     \ CompleteChanged
    "\     \ CompleteDone
    "\     \ CompleteDonePre
    "\     \ CursorHold
    "\     \ CursorHoldI
    "\     \ CursorMoved
    "\     \ CursorMovedI
    "\     \ DiffUpdated
    "\     \ DirChanged
    "\     \ DirChangedPre
    "\     \ EncodingChanged
    "\     \ ExitPre
    "\     \ FileAppendCmd
    "\     \ FileAppendPost
    "\     \ FileAppendPre
    "\     \ FileChangedRO
    "\     \ FileChangedShell
    "\     \ FileChangedShellPost
    "\     \ FileReadCmd
    "\     \ FileReadPost
    "\     \ FileReadPre
    "\     \ FileType
    "\     \ FileWriteCmd
    "\     \ FileWritePost
    "\     \ FileWritePre
    "\     \ FilterReadPost
    "\     \ FilterReadPre
    "\     \ FilterWritePost
    "\     \ FilterWritePre
    "\     \ FocusGained
    "\     \ FocusLost
    "\     \ FuncUndefined
    "\     \ GUIEnter
    "\     \ GUIFailed
    "\     \ InsertChange
    "\     \ InsertCharPre
    "\     \ InsertEnter
    "\     \ InsertLeave
    "\
    "\ syn   keyword   vimAutoEvent
    "\     \ contained
    "\     \ InsertLeavePre
    "\     \ MenuPopup
    "\     \ ModeChanged
    "\     \ OptionSet
    "\     \ QuickFixCmdPost
    "\     \ QuickFixCmdPre
    "\     \ QuitPre
    "\     \ RemoteReply
    "\     \ SearchWrapped
    "\     \ SessionLoadPost
    "\     \ ShellCmdPost
    "\     \ ShellFilterPost
    "\     \ SourceCmd
    "\     \ SourcePost
    "\     \ SourcePre
    "\     \ SpellFileMissing
    "\     \ StdinReadPost
    "\     \ StdinReadPre
    "\     \ SwapExists
    "\     \ Syntax
    "\     \ TabClosed
    "\     \ TabEnter
    "\     \ TabLeave
    "\     \ TabNew
    "\     \ TermChanged
    "\     \ TermEnter
    "\     \ TermLeave
    "\     \ TermResponse
    "\     \ TextChanged
    "\     \ TextChangedI
    "\     \ TextChangedP
    "\     \ TextYankPost
    "\     \ User
    "\     \ VimEnter
    "\     \ VimLeave
    "\     \ VimLeavePre
    "\     \ VimResized
    "\     \ VimResume
    "\     \ VimSuspend
    "\     \ WinClosed
    "\     \ WinEnter
    "\     \ WinLeave
    "\     \ WinNew
    "\     \ WinScrolled
    "\     \ BufReadPost
    "\     \ BufWrite
    "\     \ FileEncoding
    "\     \ BufCreate
    "\
    "\ syn   keyword   nvimAutoEvent
    "\ \ contained
    "\     \ TabNewEntered
    "\     \ TermClose
    "\     \ Signal
    "\     \ TermOpen
    "\     \ BufModifiedSet
    "\     \ UILeave
    "\     \ DiagnosticChanged
    "\     \ UIEnter
    "\     \ RecordingEnter
    "\     \ RecordingLeave
    "\
    "\ syn   case   match
    "\
    "\ syn   keyword   vimFuncName
    "\     \ contained
    "\     \ copy
    "\     \ complete
    "\     \ eval
    "\     \ shiftwidth
    "\     \ filter
    "\     \ delete
    "\     \ append
    "\     \ join
    "\     \ spellsuggest
    "\     \ and
    "\     \ function
    "\     \ or
    "\     \ repeat
    "\     \ string
    "\     \ winheight
    "\     \ type
    "\     \ map
    "\     \ winwidth
    "\     \ nvim_tabpage_del_var
    "\     \ nvim_tabpage_get_win
    "\     \ nvim_tabpage_get_number
    "\     \ nvim_tabpage_is_valid
    "\     \ serverstop
    "\     \ serverstart
    "\     \ haslocaldir
    "\     \ has_key
    "\     \ serverlist
    "\     \ searchpos
    "\     \ searchpairpos
    "\     \ searchpair
    "\     \ searchdecl
    "\     \ searchcount
    "\     \ nvim_win_set_width
    "\     \ screenstring
    "\     \ screenpos
    "\     \ nvim_get_hl_by_name
    "\     \ nvim_get_hl_by_id
    "\     \ screencol
    "\     \ nvim_get_hl_id_by_name
    "\     \ nvim__get_hl_defs
    "\     \ nvim_set_hl
    "\     \ screenchar
    "\     \ screenattr
    "\     \ nvim__set_hl_ns
    "\     \ nvim_feedkeys
    "\     \ rename
    "\     \ getcwd
    "\     \ nvim_input
    "\     \ indent
    "\     \ nvim_input_mouse
    "\     \ histnr
    "\     \ rpcstop
    "\     \ rpcrequest
    "\     \ rpcnotify
    "\     \ nvim_replace_termcodes
    "\     \ getwinvar
    "\     \ resolve
    "\     \ reltimefloat
    "\     \ reltime
    "\     \ reverse
    "\     \ byte2line
    "\     \ nvim_strwidth
    "\     \ extend
    "\     \ bufname
    "\     \ add
    "\     \ api_info
    "\     \ appendbufline
    "\     \ argc
    "\     \ argidx
    "\     \ arglistid
    "\     \ abs
    "\     \ floor
    "\     \ ceil
    "\     \ sqrt
    "\     \ assert_equal
    "\     \ exp
    "\     \ sin
    "\     \ cos
    "\     \ tan
    "\     \ asin
    "\
    "\ syn   keyword   vimFuncName
    "\ \ contained
    "\     \ acos
    "\     \ nvim_set_var
    "\     \ sinh
    "\     \ nvim_del_var
    "\     \ tanh
    "\     \ nvim_get_vvar
    "\     \ nvim_get_current_line
    "\     \ nvim_set_vvar
    "\     \ assert_true
    "\     \ nvim_get_option
    "\     \ atan2
    "\     \ nvim_get_option_value
    "\     \ fmod
    "\     \ assert_report
    "\     \ nvim_set_option_value
    "\     \ max
    "\     \ nvim_get_all_options_info
    "\     \ assert_equalfile
    "\     \ nvim_get_option_info
    "\     \ nvim_set_option
    "\     \ bufadd
    "\     \ bufexists
    "\     \ buffer_exists
    "\     \ buffer_name
    "\     \ buffer_number
    "\     \ bufloaded
    "\     \ bufnr
    "\     \ bufwinid
    "\     \ bufwinnr
    "\     \ byteidx
    "\     \ byteidxcomp
    "\     \ changenr
    "\     \ nvim_set_current_tabpage
    "\     \ nvim_put
    "\     \ nvim_get_color_by_name
    "\     \ nvim_get_color_map
    "\     \ nvim_get_context
    "\     \ nvim_echo
    "\     \ nvim_load_context
    "\     \ nvim_out_write
    "\     \ nvim_get_mode
    "\     \ nvim_get_keymap
    "\     \ nvim_set_keymap
    "\     \ nvim_del_keymap
    "\     \ nvim_get_commands
    "\     \ nvim_err_write
    "\     \ nvim_err_writeln
    "\     \ nvim_set_current_buf
    "\     \ nvim_list_wins
    "\     \ nvim_get_chan_info
    "\     \ nvim_list_chans
    "\     \ nvim_set_current_win
    "\     \ nvim_create_buf
    "\     \ nvim__id
    "\     \ expand
    "\     \ search
    "\     \ browsedir
    "\     \ assert_exception
    "\     \ assert_fails
    "\     \ assert_false
    "\
    "\ syn   keyword   vimFuncName
    "\ \ contained
    "\     \ assert_inrange
    "\     \ assert_match
    "\     \ assert_nobeep
    "\     \ assert_notequal
    "\     \ assert_notmatch
    "\     \ browse
    "\     \ nvim__get_runtime
    "\     \ nvim__get_lib_dir
    "\     \ nvim_get_runtime_file
    "\     \ nvim__runtime_inspect
    "\     \ nvim_list_runtime_paths
    "\     \ nvim_notify
    "\     \ len
    "\     \ getenv
    "\     \ bufload
    "\     \ filewritable
    "\     \ getfontname
    "\     \ getfperm
    "\     \ getfsize
    "\     \ getftime
    "\     \ getftype
    "\     \ getline
    "\     \ getmarklist
    "\     \ getreginfo
    "\     \ gettabinfo
    "\     \ gettabvar
    "\     \ gettabwinvar
    "\     \ globpath
    "\     \ highlight_exists
    "\     \ histdel
    "\     \ iconv
    "\     \ nvim_buf_set_name
    "\     \ inputlist
    "\     \ nvim_buf_delete
    "\     \ foldtext
    "\     \ nvim_buf_is_valid
    "\     \ interrupt
    "\     \ nvim_buf_set_mark
    "\     \ nvim_buf_get_mark
    "\     \ id
    "\     \ nvim_buf_create_user_command
    "\     \ nvim_buf_del_user_command
    "\     \ jobpid
    "\     \ nvim__buf_stats
    "\     \ jobsend
    "\     \ jobstart
    "\     \ jobstop
    "\     \ jobwait
    "\     \ json_encode
    "\     \ keys
    "\     \ nvim_set_current_line
    "\     \ nvim_open_term
    "\     \ nvim_set_current_dir
    "\     \ nvim__id_array
    "\     \ nvim_tabpage_set_var
    "\     \ nvim_get_current_tabpage
    "\     \ argv
    "\     \ nvim__id_dictionary
    "\     \ assert_beeps
    "\     \ nvim_paste
    "\     \ nvim_del_current_line
    "\
    "\ syn   keyword   vimFuncName
    "\ \ contained
    "\     \ nvim__id_float
    "\     \ cosh
    "\     \ nvim_list_tabpages
    "\     \ nvim_buf_set_extmark
    "\     \ nvim__stats
    "\     \ log
    "\     \ nvim_list_uis
    "\     \ pow
    "\     \ nvim_get_proc_children
    "\     \ min
    "\     \ nvim_get_current_win
    "\     \ nvim_buf_set_text
    "\     \ nvim_get_proc
    "\     \ execute
    "\     \ nvim_select_popupmenu_item
    "\     \ nvim_command
    "\     \ nvim_get_current_buf
    "\     \ atan
    "\     \ nvim_list_bufs
    "\     \ nvim_exec
    "\     \ nvim__inspect_cell
    "\     \ log10
    "\     \ nvim__screenshot
    "\     \ match
    "\     \ nvim_del_mark
    "\     \ insert
    "\     \ nvim_get_mark
    "\     \ remove
    "\     \ nvim_eval_statusline
    "\     \ cscope_connection
    "\     \ nvim_eval
    "\     \ nvim_create_user_command
    "\     \ nvim_call_function
    "\     \ nvim_del_user_command
    "\     \ reg_recording
    "\     \ nvim_call_dict_function
    "\     \ nvim_buf_set_keymap
    "\     \ nvim_parse_expression
    "\     \ input
    "\     \ nvim_buf_is_loaded
    "\     \ nvim_open_win
    "\     \ nvim_buf_del_mark
    "\     \ round
    "\     \ nvim_get_var
    "\     \ nvim_win_set_config
    "\     \ reg_executing
    "\     \ nvim_win_get_config
    "\     \ json_decode
    "\     \ nvim_win_get_buf
    "\     \ str2list
    "\     \ nvim_win_set_buf
    "\     \ matchstrpos
    "\     \ nvim_win_get_cursor
    "\     \ strcharpart
    "\     \ nvim_win_set_cursor
    "\     \ virtcol
    "\     \ screenchars
    "\ syn
    "\     \ keyword
    "\     \ vimFuncName
    "\     \ contained
    "\     \ nvim_win_get_height
    "\     \ mode
    "\     \ nvim_win_set_height
    "\     \ nvim_command_output
    "\     \ nvim_win_get_width
    "\     \ nextnonblank
    "\     \ nvim_win_get_var
    "\     \ readfile
    "\     \ nvim_win_set_var
    "\     \ reduce
    "\     \ nvim_win_del_var
    "\     \ nvim_buf_get_number
    "\     \ nvim_win_get_option
    "\     \ strlen
    "\     \ nvim_win_set_option
    "\     \ reg_recorded
    "\     \ nvim_win_get_position
    "\     \ nvim_buf_set_virtual_text
    "\     \ nvim_win_get_tabpage
    "\     \ nvim_get_namespaces
    "\     \ nvim_win_get_number
    "\     \ col
    "\     \ nvim_win_is_valid
    "\     \ nvim_buf_get_extmarks
    "\     \ nvim_win_hide
    "\     \ buflisted
    "\     \ nvim_win_close
    "\     \ nvim_buf_add_highlight
    "\     \ setbufline
    "\     \ setbufvar
    "\     \ setcharpos
    "\     \ setcharsearch
    "\     \ inputdialog
    "\     \ setcmdpos
    "\     \ setcursorcharpos
    "\     \ setenv
    "\     \ setfperm
    "\     \ setline
    "\     \ setloclist
    "\     \ setmatches
    "\     \ isnan
    "\     \ setpos
    "\     \ setqflist
    "\     \ setreg
    "\     \ settabvar
    "\     \ settabwinvar
    "\     \ settagstack
    "\     \ setwinvar
    "\     \ sign_jump
    "\     \ sign_placelist
    "\     \ sign_unplace
    "\     \ sign_unplacelist
    "\     \ simplify
    "\     \ sockconnect
    "\     \ stdioopen
    "\     \ matchdelete
    "\     \ msgpackdump
    "\     \ nvim_buf_line_count
    "\     \ str2float
    "\     \ mkdir
    "\     \ menu_get
    "\ syn
    "\     \ keyword
    "\     \ vimFuncName
    "\     \ contained
    "\     \ nvim_buf_attach
    "\     \ strchars
    "\     \ matchstr
    "\     \ matchlist
    "\     \ matchfuzzypos
    "\     \ matchfuzzy
    "\     \ matchend
    "\     \ nvim__buf_redraw_range
    "\     \ char2nr
    "\     \ matcharg
    "\     \ matchaddpos
    "\     \ matchadd
    "\     \ mapcheck
    "\     \ maparg
    "\     \ luaeval
    "\     \ localtime
    "\     \ list2str
    "\     \ lispindent
    "\     \ line2byte
    "\     \ line
    "\     \ libcallnr
    "\     \ libcall
    "\     \ last_buffer_nr
    "\     \ ctxset
    "\     \ ctxsize
    "\     \ cursor
    "\     \ debugbreak
    "\     \ deepcopy
    "\     \ confirm
    "\     \ dictwatcheradd
    "\     \ dictwatcherdel
    "\     \ did_filetype
    "\     \ diff_filler
    "\     \ diff_hlID
    "\     \ digraph_get
    "\     \ digraph_getlist
    "\     \ digraph_set
    "\     \ digraph_setlist
    "\     \ empty
    "\     \ environ
    "\     \ escape
    "\     \ eventhandler
    "\     \ executable
    "\     \ exepath
    "\     \ exists
    "\     \ reltimestr
    "\     \ expandcmd
    "\     \ feedkeys
    "\     \ file_readable
    "\     \ nvim_tabpage_get_var
    "\     \ rpcstart
    "\     \ filereadable
    "\     \ rubyeval
    "\     \ finddir
    "\     \ findfile
    "\     \ flatten
    "\     \ float2nr
    "\     \ screenrow
    "\     \ fnameescape
    "\     \ fnamemodify
    "\     \ foldclosed
    "\     \ foldclosedend
    "\     \ foldtextresult
    "\     \ foreground
    "\     \ fullcommand
    "\     \ funcref
    "\     \ garbagecollect
    "\     \ get
    "\     \ getbufinfo
    "\     \ getbufline
    "\     \ getbufvar
    "\     \ getchangelist
    "\     \ getchar
    "\     \ getcharmod
    "\     \ getcharpos
    "\     \ getcharsearch
    "\     \ getcharstr
    "\ syn
    "\     \ keyword
    "\     \ vimFuncName
    "\     \ contained
    "\     \ getcmdline
    "\     \ getcmdpos
    "\     \ getcmdtype
    "\     \ getcmdwintype
    "\     \ getcompletion
    "\     \ getcurpos
    "\     \ getcursorcharpos
    "\     \ sha256
    "\     \ shellescape
    "\     \ sign_define
    "\     \ sign_getdefined
    "\     \ sign_getplaced
    "\     \ getjumplist
    "\     \ sign_place
    "\     \ getloclist
    "\     \ sign_undefine
    "\     \ getmatches
    "\     \ getmousepos
    "\     \ getpid
    "\     \ getpos
    "\     \ getqflist
    "\     \ getreg
    "\     \ soundfold
    "\     \ getregtype
    "\     \ spellbadword
    "\     \ gettagstack
    "\     \ swapname
    "\     \ getwinpos
    "\     \ getwinposx
    "\     \ getwinposy
    "\     \ str2nr
    "\     \ glob
    "\     \ glob2regpat
    "\     \ strdisplaywidth
    "\     \ has
    "\     \ strgetchar
    "\     \ stridx
    "\     \ hasmapto
    "\     \ highlightID
    "\     \ nvim_buf_get_offset
    "\     \ strptime
    "\     \ strridx
    "\     \ strtrans
    "\     \ histadd
    "\     \ submatch
    "\     \ histget
    "\     \ swapinfo
    "\     \ hlID
    "\     \ hlexists
    "\     \ hostname
    "\     \ synIDtrans
    "\     \ synconcealed
    "\     \ synstack
    "\     \ system
    "\     \ systemlist
    "\     \ tabpagebuflist
    "\     \ tabpagenr
    "\     \ tabpagewinnr
    "\     \ tagfiles
    "\     \ taglist
    "\     \ isdirectory
    "\     \ isinf
    "\     \ tempname
    "\     \ termopen
    "\     \ test_garbagecollect_now
    "\     \ tr
    "\     \ timer_info
    "\     \ timer_pause
    "\     \ timer_start
    "\     \ timer_stop
    "\     \ timer_stopall
    "\     \ tolower
    "\     \ toupper
    "\     \ trim
    "\     \ trunc
    "\     \ wait
    "\     \ wildmenumode
    "\     \ win_execute
    "\     \ win_findbuf
    "\ syn
    "\     \ keyword
    "\     \ vimFuncName
    "\     \ contained
    "\     \ win_getid
    "\     \ win_gettype
    "\     \ win_gotoid
    "\     \ win_id2tabwin
    "\     \ win_id2win
    "\     \ win_move_separator
    "\     \ win_move_statusline
    "\     \ win_screenpos
    "\     \ win_splitmove
    "\     \ winbufnr
    "\     \ wincol
    "\     \ windowsversion
    "\     \ winlayout
    "\     \ winline
    "\     \ winnr
    "\     \ winrestcmd
    "\     \ winrestview
    "\     \ winsaveview
    "\     \ wordcount
    "\     \ writefile
    "\     \ xor
    "\     \ pathshorten
    "\     \ prevnonblank
    "\     \ printf
    "\     \ prompt_getprompt
    "\     \ substitute
    "\     \ nvim_get_autocmds
    "\     \ nvim_buf_del_extmark
    "\     \ prompt_setprompt
    "\     \ pum_getpos
    "\     \ pumvisible
    "\     \ py3eval
    "\     \ pyeval
    "\     \ nvim_tabpage_list_wins
    "\     \ pyxeval
    "\     \ nvim_create_autocmd
    "\     \ nvim_buf_clear_namespace
    "\     \ perleval
    "\     \ rand
    "\     \ range
    "\     \ strwidth
    "\     \ nvim_del_autocmd
    "\     \ nvim_buf_get_extmark_by_id
    "\     \ nvim_clear_autocmds
    "\     \ nvim_create_namespace
    "\     \ synID
    "\     \ nvim_create_augroup
    "\     \ nvim_buf_clear_highlight
    "\     \ synIDattr
    "\     \ prompt_setinterrupt
    "\     \ nvim_del_augroup_by_id
    "\     \ readdir
    "\     \ nvim_del_augroup_by_name
    "\     \ jobresize
    "\     \ nvim_exec_autocmds
    "\     \ jobclose
    "\     \ uniq
    "\     \ items
    "\     \ call
    "\     \ islocked
    "\     \ invert
    "\     \ cindent
    "\     \ inputsecret
    "\     \ inputsave
    "\
    "\ syn
    "\     \ keyword
    "\     \ vimFuncName
    "\     \ contained
    "\     \ inputrestore
    "\     \ undofile
    "\     \ index
    "\     \ nvim_buf_get_name
    "\     \ nvim_buf_set_option
    "\     \ nvim_buf_get_option
    "\     \ nvim_buf_del_var
    "\     \ nvim_buf_set_var
    "\     \ nvim_buf_get_commands
    "\     \ nvim_buf_del_keymap
    "\     \ split
    "\     \ nvim_buf_get_keymap
    "\     \ nvim_buf_get_changedtick
    "\     \ foldlevel
    "\     \ nvim_buf_get_var
    "\     \ nvim_buf_get_text
    "\     \ nvim_buf_set_lines
    "\     \ nvim_buf_get_lines
    "\     \ getwininfo
    "\     \ chdir
    "\     \ charcol
    "\     \ strftime
    "\     \ stdpath
    "\     \ srand
    "\     \ sort
    "\     \ test_write_list_log
    "\     \ undotree
    "\     \ values
    "\     \ visualmode
    "\     \ deletebufline
    "\     \ ctxpush
    "\     \ prompt_setcallback
    "\     \ ctxpop
    "\     \ ctxget
    "\     \ count
    "\     \ strpart
    "\     \ complete_info
    "\     \ complete_check
    "\     \ complete_add
    "\     \ clearmatches
    "\     \ charidx
    "\     \ chansend
    "\     \ chanclose
    "\     \ nr2char
    "\     \ msgpackparse
